### ISSUE TITLE
User can view the company branding

### ISSUE THREAD

**Issue by gdegas** [gdegas001/sway-finance#1]
# Motivation 

So that users can view the company branding

# tasks
- [x] create index.html
- [x] create styles.css
- [x] download company images
- [x] Link bootstrap and styles.css
- [x] add Img logo to index.html
- [x] add necessary styles to styles.css
- [x] write html code 
- [x] add files to git
- [x] commit
- [x] push it to origin
