### ISSUE TITLE
User can view navigation links

### ISSUE THREAD

**Issue by gdegas** [gdegas001/sway-finance#3]
# Motivation
Users can navigate throughout the webpage

# Tasks
- [x] create div to ecompass links
- [x] add links to the html
- [x] style the links in css to look like layout
