### ISSUE TITLE
User can view a screenshot of the Sway bot in Slack

### ISSUE THREAD

**Issue by gdegas** [gdegas001/sway-finance#7]
# Motivation 
The consumer can see what the interface of Sway bot looks like via Slack

# Tasks
- [x] download img via their website
- [x] source the image via local library to my 'index.html'
- [x] style it to fit correctly in 'styles.css'
